name: Deploy Docker Imge to Docker Hub

on:
  push:
    branches: ['main']
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4


      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Build and push to dockerhub
        uses: docker/build-push-action@v5
        with:
         context: .
         push: true
         tags: ${{ secrets.DOCKERHUB_USERNAME }}/node-app:latest
